// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jOa8Yk-b1ovWFYEgVrYNRJOU8SpF6o0',
    appId: '1:302590971270:web:1934ddea448620edb47007',
    messagingSenderId: '302590971270',
    projectId: 'society-management-userapp',
    authDomain: 'society-management-userapp.firebaseapp.com',
    storageBucket: 'society-management-userapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRRgbmyGw91_oykYx3qGSvTV8W2aQNyc',
    appId: '1:302590971270:android:5ffd687847fb8f10b47007',
    messagingSenderId: '302590971270',
    projectId: 'society-management-userapp',
    storageBucket: 'society-management-userapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkilKGaS2duAm9NtlLJ07WLdPsev8u1Ko',
    appId: '1:302590971270:ios:57b4e8e8e8449e93b47007',
    messagingSenderId: '302590971270',
    projectId: 'society-management-userapp',
    storageBucket: 'society-management-userapp.appspot.com',
    iosBundleId: 'com.example.flParkSquareSocietyGuardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkilKGaS2duAm9NtlLJ07WLdPsev8u1Ko',
    appId: '1:302590971270:ios:57b4e8e8e8449e93b47007',
    messagingSenderId: '302590971270',
    projectId: 'society-management-userapp',
    storageBucket: 'society-management-userapp.appspot.com',
    iosBundleId: 'com.example.flParkSquareSocietyGuardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jOa8Yk-b1ovWFYEgVrYNRJOU8SpF6o0',
    appId: '1:302590971270:web:1934ddea448620edb47007',
    messagingSenderId: '302590971270',
    projectId: 'society-management-userapp',
    authDomain: 'society-management-userapp.firebaseapp.com',
    storageBucket: 'society-management-userapp.appspot.com',
  );
}
